# appimage-builder recipe see https://appimage-builder.readthedocs.io for details
version: 1
script: |
  # remove any existent binaries
  rm -rf ./AppDir | true
  make install DESTDIR=AppDir
AppDir:
  path: /home/osboxes/siliconsneaker/AppDir
  app_info:
    id: siliconsneaker
    name: SiliconSneaker
    icon: siliconsneaker
    version: '1.2'
    exec: usr/bin/siliconsneaker
    exec_args: $@
  apt:
    arch:
    - amd64
    allow_unauthenticated: true
    sources:
    - sourceline: deb http://security.debian.org/debian-security bullseye-security
        main contrib
    - sourceline: deb http://deb.debian.org/debian/ bullseye-updates main contrib
        non-free
    - sourceline: deb http://deb.debian.org/debian/ bullseye main contrib non-free
    include:
    - adwaita-icon-theme
    - fonts-dejavu-core
    - hicolor-icon-theme
    - libgtk-3-0:amd64
    - libosmgpsmap-1.0-1:amd64
    - libplplot17:amd64
    - librsvg2-common:amd64
    - libxml2:amd64
  files:
    include:
    - /home/osboxes/.local/share/recently-used.xbel
    - /lib/x86_64-linux-gnu/libX11.so.6
    - /lib/x86_64-linux-gnu/libXau.so.6
    - /lib/x86_64-linux-gnu/libXcomposite.so.1
    - /lib/x86_64-linux-gnu/libXcursor.so.1
    - /lib/x86_64-linux-gnu/libXdamage.so.1
    - /lib/x86_64-linux-gnu/libXdmcp.so.6
    - /lib/x86_64-linux-gnu/libXext.so.6
    - /lib/x86_64-linux-gnu/libXfixes.so.3
    - /lib/x86_64-linux-gnu/libXi.so.6
    - /lib/x86_64-linux-gnu/libXinerama.so.1
    - /lib/x86_64-linux-gnu/libXrandr.so.2
    - /lib/x86_64-linux-gnu/libXrender.so.1
    - /lib/x86_64-linux-gnu/libatk-1.0.so.0
    - /lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0
    - /lib/x86_64-linux-gnu/libatspi.so.0
    - /lib/x86_64-linux-gnu/libblkid.so.1
    - /lib/x86_64-linux-gnu/libbrotlicommon.so.1
    - /lib/x86_64-linux-gnu/libbrotlidec.so.1
    - /lib/x86_64-linux-gnu/libbsd.so.0
    - /lib/x86_64-linux-gnu/libcairo-gobject.so.2
    - /lib/x86_64-linux-gnu/libcairo.so.2
    - /lib/x86_64-linux-gnu/libcsirocsa.so.0
    - /lib/x86_64-linux-gnu/libcsironn.so.0
    - /lib/x86_64-linux-gnu/libdatrie.so.1
    - /lib/x86_64-linux-gnu/libepoxy.so.0
    - /lib/x86_64-linux-gnu/libffi.so.7
    - /lib/x86_64-linux-gnu/libfontconfig.so.1
    - /lib/x86_64-linux-gnu/libfreetype.so.6
    - /lib/x86_64-linux-gnu/libfribidi.so.0
    - /lib/x86_64-linux-gnu/libgcrypt.so.20
    - /lib/x86_64-linux-gnu/libgdk-3.so.0
    - /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0
    - /lib/x86_64-linux-gnu/libgio-2.0.so.0
    - /lib/x86_64-linux-gnu/libglib-2.0.so.0
    - /lib/x86_64-linux-gnu/libgmodule-2.0.so.0
    - /lib/x86_64-linux-gnu/libgobject-2.0.so.0
    - /lib/x86_64-linux-gnu/libgraphite2.so.3
    - /lib/x86_64-linux-gnu/libgssapi_krb5.so.2
    - /lib/x86_64-linux-gnu/libgtk-3.so.0
    - /lib/x86_64-linux-gnu/libharfbuzz.so.0
    - /lib/x86_64-linux-gnu/libicudata.so.67
    - /lib/x86_64-linux-gnu/libicuuc.so.67
    - /lib/x86_64-linux-gnu/libidn2.so.0
    - /lib/x86_64-linux-gnu/libk5crypto.so.3
    - /lib/x86_64-linux-gnu/libkrb5.so.3
    - /lib/x86_64-linux-gnu/libkrb5support.so.0
    - /lib/x86_64-linux-gnu/libltdl.so.7
    - /lib/x86_64-linux-gnu/liblz4.so.1
    - /lib/x86_64-linux-gnu/libmd.so.0
    - /lib/x86_64-linux-gnu/libmount.so.1
    - /lib/x86_64-linux-gnu/libosmgpsmap-1.0.so.1
    - /lib/x86_64-linux-gnu/libpango-1.0.so.0
    - /lib/x86_64-linux-gnu/libpangocairo-1.0.so.0
    - /lib/x86_64-linux-gnu/libpangoft2-1.0.so.0
    - /lib/x86_64-linux-gnu/libpcre2-8.so.0
    - /lib/x86_64-linux-gnu/libpixman-1.so.0
    - /lib/x86_64-linux-gnu/libplplot.so.17
    - /lib/x86_64-linux-gnu/libpng16.so.16
    - /lib/x86_64-linux-gnu/libpsl.so.5
    - /lib/x86_64-linux-gnu/libqhull.so.8.0
    - /lib/x86_64-linux-gnu/libqsastime.so.0
    - /lib/x86_64-linux-gnu/librsvg-2.so.2
    - /lib/x86_64-linux-gnu/libshp.so.2
    - /lib/x86_64-linux-gnu/libsoup-2.4.so.1
    - /lib/x86_64-linux-gnu/libsqlite3.so.0
    - /lib/x86_64-linux-gnu/libstdc++.so.6
    - /lib/x86_64-linux-gnu/libsystemd.so.0
    - /lib/x86_64-linux-gnu/libthai.so.0
    - /lib/x86_64-linux-gnu/libunistring.so.2
    - /lib/x86_64-linux-gnu/libuuid.so.1
    - /lib/x86_64-linux-gnu/libwayland-client.so.0
    - /lib/x86_64-linux-gnu/libwayland-cursor.so.0
    - /lib/x86_64-linux-gnu/libwayland-egl.so.1
    - /lib/x86_64-linux-gnu/libxkbcommon.so.0
    - /lib/x86_64-linux-gnu/libxml2.so.2
    - /lib/x86_64-linux-gnu/libzstd.so.1
    - /usr/lib/locale/locale-archive
    - /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache
    - /usr/share//mime//mime.cache
    - /usr/share/icons/Adwaita/icon-theme.cache
    - /usr/share/icons/hicolor/icon-theme.cache

    exclude:
    - usr/share/man
    - usr/share/doc/*/README.*
    - usr/share/doc/*/changelog.*
    - usr/share/doc/*/NEWS.*
    - usr/share/doc/*/TODO.*
  runtime:
    env:
      PLPLOT_DRV_DIR: $APPDIR/usr/lib/x86_64-linux-gnu/plplot5.15.0/drivers
      PLPLOT_LIB: $APPDIR/usr/share/plplot5.15.0
  test:
    fedora-30:
      image: appimagecrafters/tests-env:fedora-30
      command: ./AppRun
      use_host_x: true
    debian-stable:
      image: appimagecrafters/tests-env:debian-stable
      command: ./AppRun
      use_host_x: true
    archlinux-latest:
      image: appimagecrafters/tests-env:archlinux-latest
      command: ./AppRun
      use_host_x: true
    centos-7:
      image: appimagecrafters/tests-env:centos-7
      command: ./AppRun
      use_host_x: true
    ubuntu-xenial:
      image: appimagecrafters/tests-env:ubuntu-xenial
      command: ./AppRun
      use_host_x: true
AppImage:
  arch: x86_64
  update-information: guess
